fuseio/fuseswap-interface

.github/workflows/tests.yaml
cypress.json
cypress/integration/add-liquidity.test.ts
cypress/integration/bridge.test.ts
cypress/integration/landing.test.ts
cypress/integration/lists.test.ts
cypress/integration/migrate-v1.test.ts
cypress/integration/remove-liquidity.test.ts
cypress/integration/swap.test.ts
cypress/integration/token-warning.ts
cypress/support/commands.js
package.json
src/components/ConnectFuseModal/index.tsx
src/components/Modal/index.tsx
src/components/NavigationTabs/index.tsx
src/components/SearchModal/ListSelect.tsx
src/components/swap/AdvancedSwapDetails.tsx
src/components/swap/SwitchNetwork.tsx
src/constants/index.ts
src/pages/Bridge/index.tsx
src/state/lists/reducer.test.ts
src/utils/index.ts
yarn.lock

added working tests, improved confirmations ux, fixed approval btn bug

---

src/components/CurrencyLogo/index.tsx
src/constants/bridge.ts
src/pages/Bridge/index.tsx
src/state/bridge/hooks.ts
src/utils/index.ts

added min and max, fixed logo issue

---

cypress/integration/lists.test.ts
package.json
src/constants/bridge.ts
src/state/bridge/hooks.ts
src/state/lists/reducer.test.ts
yarn.lock

updated tokenlist package, added new limit for g$

---

cypress/integration/bridge.test.ts
package.json
src/pages/Bridge/index.tsx
src/state/bridge/hooks.ts
src/utils/index.ts
yarn.lock

Added dynamic min max function to bridge page

added dynamic min max function

---

src/components/SearchModal/CurrencySearch.tsx
src/components/SearchModal/sorting.ts
src/state/wallet/hooks.ts

fix sort by balance

---

cypress/integration/swap.test.ts
src/hooks/useWrapCallback.ts
src/state/bridge/hooks.ts

added fixes

---

cypress/integration/lists.test.ts
src/components/AccountDetails/Transaction.tsx
src/components/FlashIcon/index.tsx
src/connectors/index.ts
src/constants/index.ts
src/pages/Bridge/index.tsx
src/state/bridge/bridges/erc20Toerc677.ts
src/state/bridge/bridges/erc677Toerc677.ts
src/state/bridge/bridges/nativeToErc.ts
src/state/bridge/bridges/tokenBridge.ts
src/state/bridge/bridges/utils.ts
src/state/bridge/hooks.ts
src/state/bridge/limits/index.ts
src/state/transactions/actions.ts
src/state/transactions/hooks.tsx
src/state/transactions/reducer.ts
src/utils/index.test.ts
src/utils/index.ts

PR Notes:
- Refactored getChainNetworkLibrary to make it more simple
- Removed ropsten from production supported chain ids
- Added better summary message for bridge transactions, shows transfer <Token> in recent transactions and shows the bridge message in pop up
- Added reduced z-index for right lightning to prevent from overlapping

Add Fuse Bridge (final)

---

src/components/FlashIcon/index.tsx
src/components/Header/index.tsx
src/pages/App.tsx
src/state/bridge/hooks.ts

PR Notes:
- Add min/max amount to respective input error
- Fix right flash icon not flashing

Enhancement: Bridge Input Errors

---

src/components/Header/index.tsx

added new styles

---

src/state/bridge/bridges/nativeToErc.ts

- Use bigNumber instead of raw wei value

Fix: Fuse -> ETH bridge transfer

---

src/components/Header/index.tsx
src/components/Menu/index.tsx

Changing info fuseswap to https

---

src/components/FlashIcon/index.tsx
src/components/Header/index.tsx
src/components/Popups/PopupItem.tsx
src/components/Popups/index.tsx
src/components/bridge/BridgeDetails.tsx
src/constants/bridge.ts
src/pages/Bridge/index.tsx
src/state/bridge/hooks.ts
src/utils/index.ts

Fix: Mobile Responsive Layout

---

src/components/bridge/BridgeDetails.tsx
src/constants/bridge.ts
src/pages/Bridge/index.tsx
src/state/bridge/hooks.ts
src/utils/index.ts

- Add Fee Block
- Add calculateBridgeFee function

Feat: Add Fee UI

---

src/components/bridge/BridgeDetails.tsx
src/pages/Bridge/index.tsx
src/state/bridge/hooks.ts
src/utils/index.ts

- Refactor to use hooks
- Add useBridgeFee and useCalculatedBridgeFee hooks

Fix: Fee UI

---

src/state/bridge/hooks.ts

- Parse bridge fee using token decimals

Fix: Bridge fee parsing

---

src/hooks/useApproveCallback.ts
src/hooks/useSwapCallback.ts

- swap and approve, only throw error if error is not 4001(user rejected transaction), moved error throw to if block

Fix: Swap and Approve errors

---

src/connectors/index.ts
src/constants/index.ts
src/hooks/useApproveCallback.ts
src/pages/AddLiquidity/index.tsx
src/pages/RemoveLiquidity/index.tsx
src/pages/Swap/index.tsx
src/state/bridge/bridges/erc20Toerc677.ts
src/state/bridge/bridges/erc677Toerc677.ts
src/state/bridge/bridges/nativeToErc.ts
src/state/bridge/hooks.ts
src/utils/index.ts

- Add more metadata to sentry errors
- Remove other wallet integrations until we test the support
- Use lodash flatmap instead of Array.prototype.flatMap

Fixes: Bugs 

---

cypress/integration/bridge.test.ts
cypress/integration/lists.test.ts
package.json
src/assets/svg/white-info.svg
src/components/FeeModal/FeeCard.tsx
src/components/FeeModal/index.tsx
src/components/SearchModal/CurrencyList.tsx
src/components/SearchModal/CurrencySearch.tsx
src/components/SearchModal/filtering.ts
src/components/TokenMigration/index.tsx
src/constants/lists.ts
src/pages/AddLiquidity/index.tsx
src/pages/Swap/index.tsx
src/state/wallet/hooks.ts
src/utils/index.ts
yarn.lock

token migrations on both lists and hide deprecated tokens

---

src/pages/Bridge/index.tsx

add warning

---

cypress/integration/add-liquidity.test.ts
src/components/TokenMigration/index.tsx
src/components/swap/SwitchNetwork.tsx
src/constants/chains.ts
src/hooks/useAddChain.ts
src/utils/index.ts

- Add switch network functionality to improve UX
- Add token to wallet when token have been migrated

Feat: Switch Network and Add Token to Wallet functionality

---

buildspec.yml

Use yarn for buildspec

---

src/components/FeeModal/index.tsx

Updates fees in the UI

---

cypress/integration/lists.test.ts
src/assets/svg/fuse-logo.svg
src/components/CurrencyLogo/index.tsx

add new fuse logo

---

src/components/WalletModal/index.tsx
src/components/Web3Status/index.tsx
src/hooks/index.ts
src/hooks/useAddChain.ts
src/pages/AddLiquidity/index.tsx
src/pages/Bridge/index.tsx
src/pages/Swap/index.tsx
src/react-app-env.d.ts
src/theme/components.tsx

feat: login auto

---

src/components/SearchModal/CurrencySearch.tsx
src/constants/index.ts

- add upgraded weth as base, 
- fix bnb not showing

hotfix: bnb and weth

---

package.json
src/components/AutoSwitchNetwork/index.tsx
src/components/WalletModal/index.tsx
src/components/Web3Status/index.tsx
src/components/swap/SwitchNetwork.tsx
src/connectors/index.ts
src/constants/index.ts
src/hooks/useAddChain.ts
src/pages/AddLiquidity/index.tsx
src/pages/Bridge/index.tsx
src/pages/Swap/index.tsx
yarn.lock

feat: walletconnect

---

src/constants/index.ts

add fusd routing and fusd common base

---

src/hooks/useRamp.ts

**PLEASE DO NOT SUBMIT TOKEN ADDITIONS AS PULL REQUESTS**
All token requests should be made via an issue.

Fixing ramp key

---

src/pages/Bridge/index.tsx
src/state/bridge/bridges/bscBnbNativeToErc20.ts
src/state/bridge/bridges/bscNativeToErc.ts
src/state/bridge/hooks.ts
src/utils/index.ts

fix: bridgeUrlParams for bscNative bridge

---

src/components/AddTokenToMetamaskButton/index.tsx
src/components/AddTokenToMetamaskModal/index.tsx
src/components/Button/index.tsx
src/components/TransactionConfirmationModal/index.tsx
src/components/swap/ConfirmSwapModal.tsx
src/pages/AddLiquidity/index.tsx
src/pages/Bridge/index.tsx
src/pages/RemoveLiquidity/index.tsx
src/state/bridge/bridges/bscBnbNativeToErc20.ts
src/state/bridge/bridges/bscErc20ToErc677.ts
src/state/bridge/bridges/bscNativeToErc.ts
src/state/bridge/bridges/erc20Toerc677.ts
src/state/bridge/bridges/erc677Toerc677.ts
src/state/bridge/bridges/nativeToErc.ts
src/state/bridge/bridges/tokenBridge.ts

- Add addTokenToMetamask to swap, pools and bridge
- Give fuse on bsc bridge relays
- Rejected transaction removes receiver address fix

Fuseswap Fixes and Feature

---

.env

**PLEASE DO NOT SUBMIT TOKEN ADDITIONS AS PULL REQUESTS**
All token requests should be made via an issue.

Moving to Pokt RPC

---

src/hooks/useRamp.ts

**PLEASE DO NOT SUBMIT TOKEN ADDITIONS AS PULL REQUESTS**
All token requests should be made via an issue.

Changing asset for Ramp

---

src/components/AutoSwitchNetwork/index.tsx
src/components/WalletModal/index.tsx
src/components/Web3Status/index.tsx
src/components/swap/SwitchNetwork.tsx
src/connectors/index.ts
src/hooks/useAddChain.ts
src/pages/AddLiquidity/index.tsx
src/pages/Bridge/index.tsx
src/pages/Swap/index.tsx
src/react-app-env.d.ts

Fixes issue when user hasn't connected the wallet to fuseswap and is on fuse but still shows switch to fuse, instead of connect wallet

Bugfix: add fix for already connected bug

---

src/constants/index.ts
src/pages/AddLiquidity/index.tsx
src/pages/Bridge/index.tsx
src/pages/RemoveLiquidity/index.tsx
src/pages/Swap/index.tsx

Reverts fuseio/fuseswap-interface#76

Revert "disable dext"

---

cypress/integration/lists.test.ts
src/components/Banner/index.tsx
src/components/Header/index.tsx
src/components/Popups/index.tsx
src/pages/App.tsx
src/static/banner.json

add ola banner

---

src/components/bridge/BridgeDetails.tsx
src/state/bridge/hooks.ts
src/state/bridge/limits/index.ts

handle errors better
issue:
https://sentry.io/share/issue/7536ab7e44e947768bc7fc3c22e2f89d/

Fix: bridge errors

---

src/components/swap/BridgeInfo.tsx
src/hooks/useAddChain.ts

- fix bug that prevents switch network from not showing

fix switch network bug
